- name: install and enable crowdsec
  hosts: localhost
  become: yes
  tasks:
    - name: remove systemd-boot-manager
      community.general.pacman:
        name:
          - systemd-boot-manager
        state: absent
    - name: install cosmos desktop
      community.general.pacman:
        name:
          - cosmic-applets-git
          - cosmic-applibrary-git
          - cosmic-bg-git
          - cosmic-comp-git
          - cosmic-edit-git
          - cosmic-files-git
          - cosmic-icons-git
          - cosmic-launcher-git
          - cosmic-notifications-git
          - cosmic-osd-git
          - cosmic-session-git
          - cosmic-settings-git
          - cosmic-term-git
          - cosmic-wallpapers-git
        state: present
        executable: paru
        update_cache: true
